version: '3'

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.1/24

services:
  alysida-master:
    build: .
    image: sidd/alysida
    container_name: alysida_master
    networks:
      - net

  peer1.alysida.com:
    image: sidd/alysida
    depends_on:
      - alysida-master
    container_name: peer1.alysida.com
    environment:
      - GUNICORN_WORKERS=5
    ports:
      - "4201:4200"
      - "5201:5200"
    command: /bin/bash -c './scripts/alysida_start.sh'
    networks:
      net:
        ipv4_address: 10.0.0.101

  peer2.alysida.com:
    image: sidd/alysida
    depends_on:
      - alysida-master
    container_name: peer2.alysida.com
    environment:
      - GUNICORN_WORKERS=5
    ports:
      - "4202:4200"
      - "5202:5200"
    command: /bin/bash -c './scripts/alysida_start.sh'
    networks:
      net:
        ipv4_address: 10.0.0.102

  peer3.alysida.com:
    image: sidd/alysida
    depends_on:
      - alysida-master
    container_name: peer3.alysida.com
    environment:
      - GUNICORN_WORKERS=5
    ports:
      - "4203:4200"
      - "5203:5200"
    command: /bin/bash -c './scripts/alysida_start.sh'
    networks:
      net:
        ipv4_address: 10.0.0.103

  mynode.alysida.com:
    image: sidd/alysida
    depends_on:
      - alysida-master
    tty: true
    container_name: mynode.alysida.com
    environment:
      - GUNICORN_WORKERS=5
    ports:
      - "4200:4200"
      - "5200:5200"
    command: /bin/bash -c './scripts/alysida_start.sh'
    networks:
      net:
        ipv4_address: 10.0.0.104