version: '3'

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.1/24

services:
  alysida-master:
    build: .
    image: sidd/alysida
    container_name: alysida_master
    networks:
      - net

  a1.alysida.com:
    image: sidd/alysida
    depends_on:
      - alysida-master
    container_name: a1.alysida.com
    environment:
      - GUNICORN_WORKERS=5
    ports:
      - "4201:4200"
    command: /bin/bash -c './scripts/alysida_start.sh'
    networks:
      net:
        ipv4_address: 10.0.0.101

  a2.alysida.com:
    image: sidd/alysida
    depends_on:
      - alysida-master
    container_name: a2.alysida.com
    environment:
      - GUNICORN_WORKERS=5
    ports:
      - "4202:4200"
    command: /bin/bash -c './scripts/alysida_start.sh'
    networks:
      net:
        ipv4_address: 10.0.0.102

  a3.alysida.com:
    image: sidd/alysida
    depends_on:
      - alysida-master
    container_name: a3.alysida.com
    environment:
      - GUNICORN_WORKERS=5
    ports:
      - "4203:4200"
    command: /bin/bash -c './scripts/alysida_start.sh'
    networks:
      net:
        ipv4_address: 10.0.0.103

  cli:
    image: sidd/alysida
    depends_on:
      - alysida-master
      - a1.alysida.com
      - a2.alysida.com
      - a3.alysida.com
    tty: true
    container_name: cli
    environment:
      - GUNICORN_WORKERS=5
    ports:
      - "4200:4200"
    command: /bin/bash -c './scripts/alysida_start.sh'
    networks:
      net:
        ipv4_address: 10.0.0.104